In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,4]])


In [3]:
a

array([[1, 2, 4]])

In [4]:
a.T
#transpose

array([[1],
       [2],
       [4]])

In [5]:
b=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

In [6]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
b[0]

array([1, 2, 3])

In [38]:
b[0][0]

1

In [39]:
b[1][0]

4

In [40]:
b[0]

array([1, 2, 3])

In [41]:
b[1]

array([4, 5, 6])

In [42]:
b[0][1]

2

In [43]:
b[:,0]

array([1, 4, 7])

In [44]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
c=np.array([[6,7,8],[2,2,2],[8,9,5]])
c

array([[6, 7, 8],
       [2, 2, 2],
       [8, 9, 5]])

In [46]:
b*5

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [47]:
c+3


array([[ 9, 10, 11],
       [ 5,  5,  5],
       [11, 12,  8]])

In [48]:
b*c


array([[ 6, 14, 24],
       [ 8, 10, 12],
       [56, 72, 45]])

In [49]:

aq=np.zeros([2,2,2])
aq

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [50]:
np.ones([4,2,3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [51]:
np.full([5,2,2],3)

array([[[3, 3],
        [3, 3]],

       [[3, 3],
        [3, 3]],

       [[3, 3],
        [3, 3]],

       [[3, 3],
        [3, 3]],

       [[3, 3],
        [3, 3]]])

In [52]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
c

array([[6, 7, 8],
       [2, 2, 2],
       [8, 9, 5]])

In [54]:
g=np.concatenate((b,c))
g

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [6, 7, 8],
       [2, 2, 2],
       [8, 9, 5]])

In [55]:
np.concatenate((b,c),axis=1)

array([[1, 2, 3, 6, 7, 8],
       [4, 5, 6, 2, 2, 2],
       [7, 8, 9, 8, 9, 5]])

In [56]:
np.vstack((b,c))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [6, 7, 8],
       [2, 2, 2],
       [8, 9, 5]])

In [57]:
np.hstack((b,c))

array([[1, 2, 3, 6, 7, 8],
       [4, 5, 6, 2, 2, 2],
       [7, 8, 9, 8, 9, 5]])

In [58]:
np.array_split(b,6)

[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([[7, 8, 9]]),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32)]

In [59]:
np.where(b==6)

(array([1], dtype=int64), array([2], dtype=int64))

In [60]:
b



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
b.min


<function ndarray.min>

In [62]:
b.min()

1

In [63]:
b.max()

9

In [64]:
b.mean()

5.0

In [65]:
np.median(b)

5.0

In [66]:
b.std()

2.581988897471611